# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa6e7cb28c98308714095e29cadde6702b1c7e44614278c33c555543dc938a7cbf57ade1e0065007017252a056eeeca460ab36e69a41733a9041378d7d536ce

test:
  secret_key_base: e64472b9e2ba36ac8a65284e9edd6f387710be10ecacb8e3efc95beb4200b3b285199df49bef1f0697759d26753e19b2151bba5ad4d08665e88d8d8fb12624ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
